directory = new Object()
directory['de'] = new Object()
directory['de']['addons.html'] = true
directory['de']['gethelp.html'] = true
directory['de']['music.html'] = true
directory['de']['photos.html'] = true
directory['de']['programs.html'] = true
directory['de']['settings.html'] = true
directory['de']['videos.html'] = true
directory['de']['weather.html'] = true
directory['de']['welcome.html'] = true
directory['de']['welcome2.html'] = true
